# Main compose file for the project

services:
  db:
    image: postgres:latest
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${POSTGRES_HOST} -p ${POSTGRES_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  master:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: master
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./master:/app
    user: root # TODO: Resolve this in production
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py init_admin &&
        python manage.py populate_test_users &&
        python manage.py runserver 0.0.0.0:8000
      "

  celery:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: celery
    command: >
      sh -c "
        echo 'Waiting for Django to be ready...' &&
        while ! curl -s http://master:8000/health/ > /dev/null; do
          echo 'Django is not ready yet...' &&
          sleep 5
        done &&
        echo 'Django is ready! Starting Celery...' &&
        celery -A core worker --loglevel=info --concurrency=4 -E -B
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root # TODO: Resolve this in production
    depends_on:
      - master
      - redis
    env_file:
      - .env

volumes:
  postgres_data: