services:
  webserver:
    build: ./webserver
    ports:
      - "2231:22"
      - "8031:80"
      - "3331:3306"
    networks:
      - corporate_network
      - backend_network

  fileserver:
    build: ./fileserver
    ports:
      - "2232:22"
      - "8032:80"
      - "9232:9200"
    networks:
      - corporate_network
      
  monitoring:
    build: ./monitoring
    ports:
      - "2233:22"
      - "8033:80"
      - "3033:3000"
      - "8090:8090"
    networks:
      - corporate_network

networks:
  corporate_network:
    driver: bridge
  backend_network:
    driver: bridge